# Generated by Django 4.0.5 on 2022-07-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0004_remove_post_author_remove_posttags_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
