# Generated by Django 4.0.5 on 2022-07-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0007_remove_account_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
