# Generated by Django 4.0.5 on 2022-07-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0008_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
