# Generated by Django 4.0.5 on 2022-07-22 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0013_upvotephoto_downvotephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('follow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
                ('upvote_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote_photo', to=settings.AUTH_USER_MODEL)),
                ('upvote_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
