# Generated by Django 4.0.5 on 2022-08-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0015_alter_history_follow_alter_history_upvote_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-id']},
        ),
    ]
