# Generated by Django 4.0.5 on 2022-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_downvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='tag'),
        ),
    ]
